/*Q13
SELECT J.CLASSICO, COUNT(*)
    FROM JOGA J JOIN PARTIDA P
    ON P.TIME1 = J.TIME1 AND P.TIME2 = J.TIME2
    WHERE EXTRACT(MONTH FROM P.DATA) <= 2
    GROUP BY J.CLASSICO;
*/

/*Q14
SELECT EXTRACT(MONTH FROM P.DATA) AS MES, COUNT(*) AS QTDE_DE_CLASSICOS
    FROM JOGA J JOIN PARTIDA P
    ON P.TIME1 = J.TIME1 AND P.TIME2 = J.TIME2
    WHERE J.CLASSICO = 'S' AND EXTRACT(YEAR FROM P.DATA) = 2018
    GROUP BY EXTRACT(MONTH FROM P.DATA)
    HAVING COUNT(*) > 1;
*/

/*Q15
SELECT T.NOME,T.ESTADO,T.SALDO_GOLS, EXTRACT(YEAR FROM P.DATA), COUNT(*) AS NUMERO_JOGOS
    FROM TIME T JOIN PARTIDA P
    ON T.NOME = P.TIME1 OR T.NOME = P.TIME2
    JOIN JOGA J
    ON P.TIME1 = J.TIME1 AND P.TIME2 = J.TIME2
    GROUP BY T.NOME,EXTRACT(YEAR FROM P.DATA)
    HAVING COUNT(*) > 0;
*/

/*Q16
SELECT
    FROM JOGA J JOIN PARTIDA P
    ON P.TIME1 = J.TIME1 AND P.TIME2 = J.TIME2
*/

/*Q17
SELECT COUNT(*) AS QTDE, AVG(SALDO_GOLS) AS MEDIA_SALDO, ESTADO, TIPO
    FROM TIME T
    GROUP BY ESTADO,TIPO
    ORDER BY TIPO,ESTADO;
*/

--Q18
SELECT J.TIME1, J.TIME2, COUNT(*) AS QTDE
    FROM JOGA J JOIN PARTIDA P
    ON J.CLASSICO = 'S'
    WHERE 
    


    

    
    

