# -*- coding: utf-8 -*-
"""trabalho1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/118QxFl2oa-CfJum-tY_DTGbal9ue3zMh

<strong>Universidade de São Paulo (USP) </strong>\
<strong>Disciplina</strong>: SCC0530 - Inteligência Artificial \
<strong>Docente</strong>: Solange Oliveira Rezende \
<strong>Discentes</strong>:
<br>&nbsp;&nbsp; Carlos Filipe de Castro Lemos (12542630)
<br>&nbsp;&nbsp; Guilherme Tranche (13671549)
<br>&nbsp;&nbsp; Henrique Gualberto Marques (13692380)
<br>&nbsp;&nbsp; João Otávio Cano (11858651)
<br>&nbsp;&nbsp; Leonardo Augusto Andrade Pereira (9039361)
<br>&nbsp;&nbsp; Pedro Santos Souza (12567502)

## Bibliotecas Utilizadas
"""

import numpy as np
import pandas as pd
import networkx as nx

import matplotlib.pyplot as plt
import seaborn as sns
import random

import time

"""## Funções de Apoio"""

def plotar_boxplot(df, title):
    '''
    Função especializada em plotar boxplot
    '''
    # Plotar boxplot com Seaborn
    plt.figure(figsize=(8, 6))
    sns.boxplot(data=df)
    plt.title(title, fontsize=16, fontweight='bold')
    plt.show()

def plotar_histograma(df, columns, labels, colors, title):
    '''
    Função especializada em plotar a distribuição de densidades.
    '''
    plt.figure(figsize=(10, 6))
    for i in range(len(columns)): plt.hist(df[columns[i]], bins=20, alpha=0.5, color=colors[i], label=labels[i])
    plt.xlabel('Total de Caminhos')
    plt.ylabel('Densidade')
    plt.title(title, fontsize=16, fontweight='bold')
    plt.legend()
    plt.show()

def trace_route(G, path, title):
    '''
    Função especializado em traçar a rota percorrida
    no grafo e plotar o resultado final.
    '''
    # Exibir o resultado
    if path:
        print("Caminho encontrado:", path)
    else:
        print("Não foi possível encontrar um caminho do estado inicial ao estado final.")

    # Adicionar atributos aos vértices e arestas que fazem parte do caminho
    path_edges = [(path[i], path[i+1]) for i in range(len(path)-1)]
    path_nodes = set(path)

    # Desenhar o grafo
    pos = nx.spring_layout(G)
    nx.draw(G, pos, with_labels=True, node_color="skyblue", node_size=500, font_size=12, font_weight="bold")

    # Desenhar as arestas do caminho em vermelho e destacar os vértices
    nx.draw_networkx_edges(G, pos, edgelist=path_edges, edge_color='red', width=2)
    nx.draw_networkx_nodes(G, pos, nodelist=path_nodes, node_color='red', node_size=500)

    # Adicionar rótulos de peso das arestas
    labels = nx.get_edge_attributes(G, 'weight')
    nx.draw_networkx_edge_labels(G, pos, edge_labels=labels)

    plt.title(title, fontsize=16, fontweight='bold')
    plt.show()

def graph_plot(G, title):
    '''
    Função especializado em plotar o grafo do trânsito
    com seus respectivos pesos. Cada peso simboliza
    dificuldades enfrentadas pelo entregador. Quanto
    maior o seu valor, mais dificil e demorado é o
    trajeto entre dois vértices.
    '''
    # Definir layout para plotagem
    pos = nx.spring_layout(G)
    nx.draw(G, pos, with_labels=True, node_size=700, node_color="skyblue", font_size=10, font_weight="bold")

    # Adicionar rótulos de peso das arestas
    labels = nx.get_edge_attributes(G, 'weight')
    nx.draw_networkx_edge_labels(G, pos, edge_labels=labels)

    # Exibir o gráfico
    plt.title(title, fontsize=16, fontweight='bold')
    plt.show()

def dfs(graph, start, target, visited=None, path=None):
    '''
    Função de busca em profundidade. Ela recebe o
    grafo e faz uma busca cega entre o estado inicial
    (start) e o estado final (target).
    '''
    if visited is None:
        visited = set()
    if path is None:
        path = []

    visited.add(start)
    path = path + [start]

    if start == target:
        return path

    for neighbor in graph.neighbors(start):
        if neighbor not in visited:
            new_path = dfs(graph, neighbor, target, visited, path)
            if new_path:
                return new_path
    return None

"""## Exemplo de Funcionamento

Nesse tópico, realizamos algumas definições básicas para exemplificar o funcionamento da resolução do problema do entregador de aplicativo.

Assim, fixamos o estado inicial (onde ele coleta o pedido) e o estado final (onde o pedido é entregue ao cliente).

Além disso, fixamos o tráfego de acordo com o grafo delimitado abaixo. Cada vértice representa uma localidade diferente, sendo que cada aresta representa o caminho entre uma localidade e outra, lembrando que as dificuldades de locomoção estão definidas nos pesos das arestas.
"""

# Definir estado inicial e estado final
start_state = 1
target_state = 10

# Criação de um grafo de exemplo
G = nx.Graph()
G.add_weighted_edges_from([
    (1, 5, 7), (1, 6, 10), (2, 10, 9), (2, 5, 2),
    (3, 4, 4), (4, 8, 5), (4, 5, 5), (4, 7, 1),
    (4, 9, 8), (5, 8, 1), (5, 10, 5), (6, 9, 8),
    (6, 10, 4), (6, 7, 5), (7, 10, 10), (7, 8, 5)
])

# Exibição do Grafo
graph_plot(G, "Grafo do Trânsito")

"""## Busca em Profundidade

Utilizaremos o algoritmo de Busca em Profundidade (DFS) para realizar uma busca cega no espaço amostral. Assim, poderemos mostrar que ele irá percorrer todos os caminhos para encontrar uma trajetória entre o estado inicial e o estado final, mas irá retornar o primeiro caminho que satisfaça tal condição. Esse algoritmo não é otimizado para encontrar a melhor solução, embora execute de forma bastante rápida.

No contexto do trabalho, o algoritmo representa o entregador de aplicativo que não sabe onde deve chegar, mas, enfrentando toda sorte de problemas de trânsito e condições adversas, testa todos os caminhos até encontrar a localidade alvo.
"""

path = dfs(G, start_state, target_state)
trace_route(G,path,"Caminho em Busca em Profundidade")

"""## Busca Heurística com A* ou A-Star

Utilizando o algoritmo A* (A-Estrela ou A-Star), podemos realizar uma busca herística nos vértices, de modo a encontrar a solução ótima para atingir o resultado desejado. Esse é um algoritmo que funciona de forma ótima, mas exige recursos computacionais para realizar os cálculos. Além disso, costuma ser muito mais devagar que a busca em profundidade.

No contexto do trabalho, o algoritmo representa o entregar de aplicativos experiente, que conhece o trânsito e está atento às condições climáticas. Desse modo, pode escolher os caminhos mais pertos e mais rápidos para realizar a entrega.
"""

path = nx.astar_path(G, start_state, target_state)
trace_route(G,path,"Caminho em A*")

"""## Estatísticas Comparativas de Interpretação

Para realizar uma comparação mais justa entre os dois algoritmos, realizamos um teste estatístico que consiste em coletar dados experimentais de tamanho de caminho e de tempo gasto na execução do algoritmo. Esse experimento pode ser descrito como a realização de entregas por um entregar de aplicativo, de modo que, a cada execução do experimento, estaremos escolhendo aleatoriamente o estado inicial e o estado final. Assim, esses estados serão submetidos aos algoritmos de DFS e de AStar e os dados serão medidos e coletados. Posteriormente, iremos analisar estatisticamente os resultados obtidos.
"""

# Preparação das listas para coletar dados
lista_vertices = list(G.nodes())
dist_dfs_tam = []
dist_dfs_tempo = []
dist_ast_tam = []
dist_ast_tempo = []

# Simulação de 100 experimentos
for i in range(100):

    # Escolha aleatória do começo e do fim das rotas
    start = random.choice(lista_vertices)
    end = random.choice(lista_vertices)

    # Coleta dos dados de tempo e de tamanho para a busca em profundidade
    inicio = time.time()
    pathDFS = dfs(G, start, end)
    fim = time.time()
    dist_dfs_tempo.append(fim-inicio)
    dist_dfs_tam.append(len(pathDFS))

    # Coleta dos dados de tempo e de tamanho para a busca A-Star
    inicio = time.time()
    pathASTAR = nx.astar_path(G, start, end)
    fim = time.time()
    dist_ast_tempo.append(fim-inicio)
    dist_ast_tam.append(len(pathASTAR))

"""## Descrição Estatística

A descrição estatística dos dados faz um resumo dos valores estatísticos médios obtidos com as distribuições coletadas. Nesse contexto, podemos perceber o tamanho médio dos caminhos é menor para o A-Star (2.70 u.a.m.) em face do DFS (5.06 u.a.m), assim como podemos verificar que o algoritmo DFS é mais rápido ($2.4*10^{-6}s$) que o A-Star ($7*10^{-6}s$). Para analisar melhor os outros valores, utilizaremos o boxplot e um gráfico de distribuição. Dessa forma, poderemos ver como os valores estão distribuídos.
"""

# Utilização do pandas para simplificar cálculos e gráficos
df = pd.DataFrame({
    'DFS (Tamanho)': dist_dfs_tam,
    'A-Star (Tamanho)': dist_ast_tam,
    'A-Star (Tempo)': dist_ast_tempo,
    'DFS (Tempo)': dist_dfs_tempo
})

# Descrição estatística dos dados
df.describe()

"""### Análise do Tamanho dos Caminhos

Através dos dois gráficos abaixo, temos nitidamente que os tamanhos dos caminhos percorridos pelo DFS são maiores que os percorridos pelo A-Star. Isso mostra e corrobora a característica do algoritmo heurístico de encontrar a solução ótima para o problema.
"""

plotar_boxplot(
    df[['DFS (Tamanho)','A-Star (Tamanho)']],
    'Boxplot - Tamanho dos Caminhos')

plotar_histograma(df,
    ['A-Star (Tamanho)','DFS (Tamanho)'],
    ['A-Star', 'DFS'],
    ['blue','orange'],
    'Distribuição dos Tamanhos dos Caminhos')

"""### Análise do Tempo de Execução dos Algoritmos

De acordo com os gráficos abaixo, constatamos que o algoritmo A-Star é o que mais gasta tempo de execução em face do algoritmo DFS. Isso ocorre porque, na busca da melhor solução, o algoritmo realiza mais cálculos.
"""

plotar_boxplot(
    df[['A-Star (Tempo)','DFS (Tempo)']],
    'Boxplot - Tempo dos Algoritmos')

plotar_histograma(df,
    ['DFS (Tempo)','A-Star (Tempo)'],
    ['DFS','A-Star'],
    ['blue','orange'],
    'Distribuição dos Tempos do Algoritmo')