CREATE TABLE PESSOA (
    CPF CHAR(14) NOT NULL,
    DATANASC DATE NOT NULL,
    IDADE NUMBER(3) NOT NULL,
    NOME VARCHAR2(50) NOT NULL,
    PESO NUMBER(5,2) NOT NULL, -- 5 dígitos no total, 2 para as casas decimais
    ALTURA NUMBER(3) NOT NULL, -- Altura em cm
    TELEFONE VARCHAR2(15),
    CONSTRAINT PK_PESSOA PRIMARY KEY (CPF),
    CONSTRAINT CK_CPF_PESSOA CHECK (REGEXP_LIKE(CPF, '[0-9]{3}\.[0-9]{3}\.[0-9]{3}\-[0-9]{2}')) -- Checa formato do CPF
);

CREATE TABLE ENDERECO (
    PESSOA CHAR(14) NOT NULL,
    CEP CHAR(10) NOT NULL,
    RUA VARCHAR2(50) NOT NULL,
    NUMERO VARCHAR2(10) NOT NULL,
    BAIRRO VARCHAR2(30) NOT NULL,
    CIDADE VARCHAR2(30) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    CONSTRAINT PK_ENDERECO PRIMARY KEY (PESSOA),
    CONSTRAINT FK_ENDERECO_PESSOA FOREIGN KEY (PESSOA) REFERENCES PESSOA(CPF) ON DELETE CASCADE
);

CREATE TABLE DEFICIENCIAS (
    PESSOA CHAR(14) NOT NULL,
    DESCRICAO VARCHAR2(200),
    CONSTRAINT PK_DEFICIENCIAS PRIMARY KEY (PESSOA, DESCRICAO), -- Deixei 1:N, tava 1:1 no relacional, dps deleta esse comentário
    CONSTRAINT FK_DEFICIENCIAS_PESSOA FOREIGN KEY (PESSOA) REFERENCES PESSOA(CPF) ON DELETE CASCADE
);

CREATE TABLE MAIOR (
    CPF CHAR(14) NOT NULL,
    CONSTRAINT PK_MAIOR PRIMARY KEY (CPF),
    CONSTRAINT FK_MAIOR_PESSOA FOREIGN KEY (CPF) REFERENCES PESSOA(CPF) ON DELETE CASCADE
);

CREATE TABLE MENOR (
    CPF CHAR(14) NOT NULL,
    RESPONSAVEL CHAR(14) NOT NULL,
    CONSTRAINT PK_MENOR PRIMARY KEY (CPF),
    CONSTRAINT FK_MENOR_PESSOA FOREIGN KEY (CPF) REFERENCES PESSOA(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_MENOR_RESPONSAVEL FOREIGN KEY (RESPONSAVEL) REFERENCES MAIOR(CPF) -- Impede a exclusão do responsável, que causaria inconsistência
);

CREATE TABLE DIRETOR (
    CPF CHAR(14) NOT NULL,
    NOME VARCHAR2(50) NOT NULL,
    DATANASC DATE NOT NULL,
    CONSTRAINT PK_DIRETOR PRIMARY KEY (CPF),
    CONSTRAINT CK_CPF_DIRETOR CHECK (REGEXP_LIKE(CPF, '[0-9]{3}\.[0-9]{3}\.[0-9]{3}\-[0-9]{2}')) -- Checa formato do CPF
);

CREATE TABLE SECRETARIA_ESPORTE (
    MUNICIPIO VARCHAR2(50) NOT NULL,
    NOME VARCHAR2(50) NOT NULL,
    DIRETOR CHAR(14) NOT NULL,
    CONSTRAINT PK_SECRETARIA_ESPORTE PRIMARY KEY (MUNICIPIO),
    CONSTRAINT UQ_SECRETARIA_DIRETOR UNIQUE(DIRETOR),
    CONSTRAINT FK_SECRETARIA_DIRETOR FOREIGN KEY (DIRETOR) REFERENCES DIRETOR(CPF) -- Não permite excluir o diretor, que causaria inconsistência
);

CREATE TABLE FUNCIONARIO (
    CPF CHAR(14) NOT NULL,
    NOME VARCHAR2(50) NOT NULL,
    DATANASC DATE NOT NULL,
    TIPO VARCHAR2(12) NOT NULL,
    UNIDADE VARCHAR2(50) NOT NULL, -- Sem chave secundária, ficou 1:N, tirar esse comentário dps
    CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (CPF),
    CONSTRAINT CK_CPF_FUNCIONARIO CHECK (REGEXP_LIKE(CPF, '[0-9]{3}\.[0-9]{3}\.[0-9]{3}\-[0-9]{2}')), -- Checa formato do CPF
    CONSTRAINT CK_TIPO CHECK(UPPER(TIPO) IN('RESPONSAVEL', 'PERSONAL')),
    CONSTRAINT FK_FUNCIONARIO_UNIDADE FOREIGN KEY (UNIDADE) REFERENCES SECRETARIA_ESPORTE(MUNICIPIO) ON DELETE CASCADE
);

CREATE TABLE RESPONSAVEL (
    CPF CHAR(14) NOT NULL,
    CERTIFICACAO VARCHAR2(50) NOT NULL,
    ANOSEXP NUMBER(2) NOT NULL,
    CONSTRAINT PK_RESPONSAVEL PRIMARY KEY (CPF),
    CONSTRAINT FK_RESPONSAVEL FOREIGN KEY (CPF) REFERENCES FUNCIONARIO(CPF) ON DELETE CASCADE
);

CREATE TABLE MODALIDADE (
    NOME VARCHAR2(50) NOT NULL,
    UNIDADE VARCHAR2(50) NOT NULL,
    LOCAL VARCHAR2(50),
    RESPONSAVEL CHAR(14) NOT NULL,
    MENOR NUMBER(1),  --0 não permite, 1 permite
    CONSTRAINT PK_MODALIDADE PRIMARY KEY (NOME, UNIDADE),
    CONSTRAINT UQ_MODALIDADE_RESPONSAVEL UNIQUE(RESPONSAVEL),
    CONSTRAINT UQ_MODALIDADE_NOME UNIQUE(NOME), -- Nome precisa ser único já que é referenciado pela FK de personal
    CONSTRAINT FK_MODALIDADE_RESPONSAVEL FOREIGN KEY (RESPONSAVEL) REFERENCES RESPONSAVEL(CPF), -- Não permite excluir o responsável, que causaria inconsistência
    CONSTRAINT FK_MODALIDADE_UNIDADE FOREIGN KEY (UNIDADE) REFERENCES SECRETARIA_ESPORTE(MUNICIPIO) ON DELETE CASCADE
);

CREATE TABLE PERSONAL (
    CPF CHAR(14) NOT NULL,
    AREA VARCHAR2(50) NOT NULL, -- Não está not null no MR, mas acho que faz sentido
    PRECO NUMBER(7,2), -- 7 dígitos no total, 2 para as casas decimais
    ANOSEXP NUMBER(2),
    MODALIDADE VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_PERSONAL PRIMARY KEY (CPF),
    CONSTRAINT FK_PERSONAL_PESSOA FOREIGN KEY (CPF) REFERENCES FUNCIONARIO(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_PERSONAL_MODALIDADE FOREIGN KEY (MODALIDADE) REFERENCES MODALIDADE(NOME) ON DELETE SET NULL -- Personal não precisa de uma modalidade pra estar no banco
);

CREATE TABLE TREINO_PARTICULAR (
    PESSOA CHAR(14) NOT NULL,
    PERSONAL CHAR(14) NOT NULL,
    DATA_HORA TIMESTAMP NOT NULL,
    LOCAL VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_TREINO_PARTICULAR PRIMARY KEY (PESSOA, PERSONAL, DATA_HORA),
    CONSTRAINT FK_TREINO_PESSOA FOREIGN KEY (PESSOA) REFERENCES PESSOA(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_TREINO_PERSONAL FOREIGN KEY (PERSONAL) REFERENCES PERSONAL(CPF) ON DELETE CASCADE
);

CREATE TABLE MATRICULA (
    PESSOA CHAR(14) NOT NULL,
    MODALIDADE VARCHAR2(50) NOT NULL,
    UNIDADE VARCHAR2(50) NOT NULL,
    DATA_HORA TIMESTAMP NOT NULL,
    CONSTRAINT PK_MATRICULA PRIMARY KEY (PESSOA, MODALIDADE, UNIDADE, DATA_HORA),
    CONSTRAINT FK_MATRICULA_PESSOA FOREIGN KEY (PESSOA) REFERENCES PESSOA(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_MATRICULA_MODALIDADE FOREIGN KEY (MODALIDADE, UNIDADE) REFERENCES MODALIDADE(NOME, UNIDADE) ON DELETE CASCADE
);
